// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tyted.API.Data;

#nullable disable

namespace Tyted.API.Migrations
{
    [DbContext(typeof(TytedContext))]
    [Migration("20251211215145_InventarioInicial")]
    partial class InventarioInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Tyted.API.Models.Producto", b =>
                {
                    b.Property<int>("CodigoProd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodigoProd"));

                    b.Property<int>("CodigoProv")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("StockActual")
                        .HasColumnType("int");

                    b.Property<string>("TipoArt")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CodigoProd");

                    b.HasIndex("CodigoProv");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("Tyted.API.Models.ProductoUnidad", b =>
                {
                    b.Property<int>("IdProductoUnidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProductoUnidad"));

                    b.Property<int>("CantidadEquivalente")
                        .HasColumnType("int");

                    b.Property<int>("CodigoProd")
                        .HasColumnType("int");

                    b.Property<decimal>("CostoUnitarioMonedaBase")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("CostoUnitarioMonedaExt")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<int>("IdUnidad")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioMonedaBase")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("PrecioMonedaExt")
                        .HasColumnType("decimal(18, 4)");

                    b.HasKey("IdProductoUnidad");

                    b.HasIndex("CodigoProd");

                    b.HasIndex("IdUnidad");

                    b.ToTable("ProductosUnidad");
                });

            modelBuilder.Entity("Tyted.API.Models.Proveedor", b =>
                {
                    b.Property<int>("CodigoProv")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodigoProv"));

                    b.Property<string>("Contacto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cuentaasociadaconta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonaISLR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RIF")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Razonsocial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CodigoProv");

                    b.ToTable("Proveedores");
                });

            modelBuilder.Entity("Tyted.API.Models.UnidadMedida", b =>
                {
                    b.Property<int>("IdUnidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUnidad"));

                    b.Property<string>("NombreUnidad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdUnidad");

                    b.ToTable("UnidadesMedida");
                });

            modelBuilder.Entity("Tyted.API.Models.Producto", b =>
                {
                    b.HasOne("Tyted.API.Models.Proveedor", "Proveedor")
                        .WithMany()
                        .HasForeignKey("CodigoProv")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("Tyted.API.Models.ProductoUnidad", b =>
                {
                    b.HasOne("Tyted.API.Models.Producto", "Producto")
                        .WithMany("UnidadesDeVenta")
                        .HasForeignKey("CodigoProd")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tyted.API.Models.UnidadMedida", "Unidad")
                        .WithMany()
                        .HasForeignKey("IdUnidad")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("Unidad");
                });

            modelBuilder.Entity("Tyted.API.Models.Producto", b =>
                {
                    b.Navigation("UnidadesDeVenta");
                });
#pragma warning restore 612, 618
        }
    }
}
