// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tyted.API.Data;

#nullable disable

namespace Tyted.API.Migrations
{
    [DbContext(typeof(TytedContext))]
    [Migration("20261004104346_AddAccountingSchema")]
    partial class AddAccountingSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Tyted.API.Models.AbonoCXC", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CuentaPorCobrarId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaAbono")
                        .HasColumnType("datetime2");

                    b.Property<string>("MetodoPago")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("MontoAbonadoMonedaBase")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<string>("Notas")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AbonosCXC");
                });

            modelBuilder.Entity("Tyted.API.Models.AsientoContable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime>("FechaComprobante")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("NumeroComprobante")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("PeriodoContableId")
                        .HasColumnType("int");

                    b.Property<string>("TipoComprobante")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("TotalDebe")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("TotalHaber")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PeriodoContableId");

                    b.ToTable("AsientosContables");
                });

            modelBuilder.Entity("Tyted.API.Models.AsientoDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AsientoContableId")
                        .HasColumnType("int");

                    b.Property<int>("CuentaContableId")
                        .HasColumnType("int");

                    b.Property<decimal>("Debe")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("Haber")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<string>("Referencia")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("AsientoContableId");

                    b.HasIndex("CuentaContableId");

                    b.ToTable("AsientosDetalles");
                });

            modelBuilder.Entity("Tyted.API.Models.AuditoriaContable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("AsientoContableId")
                        .HasColumnType("int");

                    b.Property<string>("Detalle")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("AsientoContableId");

                    b.ToTable("AuditoriasContables");
                });

            modelBuilder.Entity("Tyted.API.Models.CajaSesion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaApertura")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsAbierta")
                        .HasColumnType("bit");

                    b.Property<decimal>("MontoAperturaUSD")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal?>("MontoCierreEfectivoUSD")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal?>("MontoCierrePagoMovilUSD")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<string>("ObservacionesCierre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Usuario")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CajaSesiones");
                });

            modelBuilder.Entity("Tyted.API.Models.Categoria", b =>
                {
                    b.Property<int>("IdCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCategoria"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("PorcentajeMargen")
                        .HasColumnType("decimal(5, 2)");

                    b.HasKey("IdCategoria");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("Tyted.API.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("LimiteCreditoUSD")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("PermitirCredito")
                        .HasColumnType("bit");

                    b.Property<string>("Rif")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Rif")
                        .IsUnique();

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Tyted.API.Models.Compra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AplicaLibroCompras")
                        .HasColumnType("bit");

                    b.Property<int>("CodigoProv")
                        .HasColumnType("int");

                    b.Property<bool>("EsCredito")
                        .HasColumnType("bit");

                    b.Property<bool>("EsGastoServicio")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCompra")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaVencimiento")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsAnulada")
                        .HasColumnType("bit");

                    b.Property<decimal>("IvaMonedaBase")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("IvaMonedaExt")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<string>("NumeroControl")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NumeroFactura")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("SubtotalMonedaBase")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("SubtotalMonedaExt")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("TasaDeCambio")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<string>("TipoMoneda")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<decimal>("TotalMonedaBase")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("TotalMonedaExt")
                        .HasColumnType("decimal(18, 4)");

                    b.HasKey("Id");

                    b.HasIndex("CodigoProv");

                    b.ToTable("Compras");
                });

            modelBuilder.Entity("Tyted.API.Models.CompraDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<string>("CodigoProd")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CompraId")
                        .HasColumnType("int");

                    b.Property<decimal>("CostoUnitarioMonedaBase")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("CostoUnitarioMonedaExt")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<int>("IdProductoUnidad")
                        .HasColumnType("int");

                    b.Property<decimal>("IvaLineaMonedaExt")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("SubtotalLineaMonedaBase")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("SubtotalLineaMonedaExt")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("TasaIVA")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("TotalLineaMonedaBase")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("TotalLineaMonedaExt")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<string>("UnidadCompra")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CodigoProd");

                    b.HasIndex("CompraId");

                    b.ToTable("ComprasDetalle");
                });

            modelBuilder.Entity("Tyted.API.Models.CuentaContable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AceptaCentroCosto")
                        .HasColumnType("bit");

                    b.Property<bool>("AceptaTerceros")
                        .HasColumnType("bit");

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<string>("CodigoCuenta")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<bool>("EsMovimiento")
                        .HasColumnType("bit");

                    b.Property<string>("Naturaleza")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("Nivel")
                        .HasColumnType("int");

                    b.Property<string>("NombreCuenta")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("PadreCuentaId")
                        .HasColumnType("int");

                    b.Property<string>("TipoCuenta")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("PadreCuentaId");

                    b.HasIndex("EmpresaId", "CodigoCuenta")
                        .IsUnique();

                    b.ToTable("CuentasContables");
                });

            modelBuilder.Entity("Tyted.API.Models.CuentaPorCobrar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaVencimiento")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("MontoTotalUSD")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("SaldoPendienteUSD")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<int>("VentaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VentaId");

                    b.ToTable("CuentasPorCobrar");
                });

            modelBuilder.Entity("Tyted.API.Models.CuentaPorPagar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompraId")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaVencimiento")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("MontoTotalUSD")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("SaldoPendienteUSD")
                        .HasColumnType("decimal(18, 4)");

                    b.HasKey("Id");

                    b.HasIndex("CompraId");

                    b.ToTable("CuentasPorPagar");
                });

            modelBuilder.Entity("Tyted.API.Models.Empresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Direccion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LeyendaFactura")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RIF")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TipoContribuyente")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Empresa");
                });

            modelBuilder.Entity("Tyted.API.Models.EmpresaConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("EmpresaConfigs");
                });

            modelBuilder.Entity("Tyted.API.Models.InventarioMovimiento", b =>
                {
                    b.Property<int>("IdMovimiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMovimiento"));

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<string>("CodigoProd")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("CompraId")
                        .HasColumnType("int");

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("CostoUnitarioUSD")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdMovimiento");

                    b.HasIndex("CodigoProd");

                    b.HasIndex("CompraId");

                    b.ToTable("InventarioMovimientos");
                });

            modelBuilder.Entity("Tyted.API.Models.Moneda", b =>
                {
                    b.Property<int>("IdMoneda")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMoneda"));

                    b.Property<bool>("EsMonedaBase")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Siglas")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.HasKey("IdMoneda");

                    b.ToTable("Monedas");
                });

            modelBuilder.Entity("Tyted.API.Models.NotaEntregaCompra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaRecepcion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdProductoUnidad")
                        .HasColumnType("int");

                    b.Property<string>("NumeroNota")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ProcesadoAFactura")
                        .HasColumnType("bit");

                    b.Property<int>("ProveedorId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalEstimadoUSD")
                        .HasColumnType("decimal(18, 4)");

                    b.HasKey("Id");

                    b.ToTable("NotasEntregaCompra");
                });

            modelBuilder.Entity("Tyted.API.Models.NotaEntregaCompraDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CantidadRecibida")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<string>("CodigoProd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("CostoUnitarioUSD")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<int>("NotaEntregaCompraId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NotaEntregaCompraId");

                    b.ToTable("NotasEntregaCompraDetalle");
                });

            modelBuilder.Entity("Tyted.API.Models.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("MontoTotalUSD")
                        .HasColumnType("decimal(18, 4)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("Tyted.API.Models.PedidoDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Cantidad")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<string>("CodigoProd")
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("IdProductoUnidad")
                        .HasColumnType("int");

                    b.Property<int?>("PedidoId")
                        .HasColumnType("int");

                    b.Property<decimal?>("PrecioUnitarioUSD")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal?>("SubtotalUSD")
                        .HasColumnType("decimal(18, 4)");

                    b.HasKey("Id");

                    b.HasIndex("CodigoProd");

                    b.HasIndex("IdProductoUnidad");

                    b.HasIndex("PedidoId");

                    b.ToTable("PedidosDetalle");
                });

            modelBuilder.Entity("Tyted.API.Models.PeriodoContable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Anio")
                        .HasColumnType("int");

                    b.Property<bool>("Cerrado")
                        .HasColumnType("bit");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("Mes")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "Anio", "Mes")
                        .IsUnique();

                    b.ToTable("PeriodosContables");
                });

            modelBuilder.Entity("Tyted.API.Models.Producto", b =>
                {
                    b.Property<string>("CodigoProd")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CodigoBarras")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CodigoProv")
                        .HasColumnType("int");

                    b.Property<decimal>("CostoUnitarioBase")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(510)
                        .HasColumnType("nvarchar(510)");

                    b.Property<DateTime>("FechaAdquisicion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaVencimiento")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdCategoria")
                        .HasColumnType("int");

                    b.Property<int>("IdTasaIVA")
                        .HasColumnType("int");

                    b.Property<decimal?>("ImpuestoLicorPorcentaje")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<bool?>("ManejaImpuestoLicor")
                        .HasColumnType("bit");

                    b.Property<bool>("PermiteDesglose")
                        .HasColumnType("bit");

                    b.Property<decimal>("StockActual")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("StockMinimo")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<string>("TipoArt")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CodigoProd");

                    b.HasIndex("CodigoProv");

                    b.HasIndex("IdCategoria");

                    b.HasIndex("IdTasaIVA");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("Tyted.API.Models.ProductosUnidad", b =>
                {
                    b.Property<int>("IdProductoUnidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProductoUnidad"));

                    b.Property<decimal>("CantidadEquivalente")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<string>("CodigoBarras")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CodigoProd")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("CostoUnitarioMonedaBase")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal?>("CostoUnitarioMonedaExt")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<int>("IdUnidad")
                        .HasColumnType("int");

                    b.Property<decimal?>("Margen1")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal?>("Margen2")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal?>("Margen3")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<string>("NombreUnidad")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("Precio2MonedaBase")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal?>("Precio2MonedaExt")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal?>("Precio3MonedaBase")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal?>("Precio3MonedaExt")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal?>("PrecioMonedaBase")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal?>("PrecioMonedaExt")
                        .HasColumnType("decimal(18, 4)");

                    b.HasKey("IdProductoUnidad");

                    b.HasIndex("CodigoProd");

                    b.HasIndex("IdUnidad");

                    b.ToTable("ProductosUnidad");
                });

            modelBuilder.Entity("Tyted.API.Models.Proveedor", b =>
                {
                    b.Property<int>("CodigoProv")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodigoProv"));

                    b.Property<string>("Contacto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cuentaasociadaconta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonaISLR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RIF")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Razonsocial")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CodigoProv");

                    b.ToTable("Proveedores");
                });

            modelBuilder.Entity("Tyted.API.Models.TasaDeCambio", b =>
                {
                    b.Property<int>("IdTasa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTasa"));

                    b.Property<decimal?>("FactorSugerido")
                        .HasColumnType("decimal(18, 6)");

                    b.Property<DateTime>("FechaVigencia")
                        .HasColumnType("datetime2");

                    b.Property<string>("MonedaDestino")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MonedaOrigen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreTasa")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Tasa")
                        .HasColumnType("decimal(18, 6)");

                    b.Property<string>("UsuarioRegistro")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdTasa");

                    b.ToTable("TasaDeCambio");
                });

            modelBuilder.Entity("Tyted.API.Models.TasaIVA", b =>
                {
                    b.Property<int>("IdTasaIVA")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTasaIVA"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Porcentaje")
                        .HasColumnType("decimal(5, 2)");

                    b.HasKey("IdTasaIVA");

                    b.ToTable("TasasIVA");
                });

            modelBuilder.Entity("Tyted.API.Models.UnidadMedida", b =>
                {
                    b.Property<int>("IdUnidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUnidad"));

                    b.Property<string>("NombreUnidad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdUnidad");

                    b.ToTable("UnidadesMedida");
                });

            modelBuilder.Entity("Tyted.API.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("NombreCompleto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rol")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Tyted.API.Models.Venta", b =>
                {
                    b.Property<int>("VentaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VentaId"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<bool>("EsCredito")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaVencimiento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaVenta")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsAnulada")
                        .HasColumnType("bit");

                    b.Property<decimal>("IvaMonedaBase")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("IvaMonedaExt")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<string>("MetodoPago")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroFactura")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("PedidoId")
                        .HasColumnType("int");

                    b.Property<decimal>("SubtotalMonedaBase")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("SubtotalMonedaExt")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("TasaDeCambio")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal?>("TasaDia")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<string>("TipoMoneda")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalMonedaBase")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("TotalMonedaExt")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal?>("TotalUSD")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal?>("TotalVES")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<string>("Usuario")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("VentaId");

                    b.HasIndex("ClienteId");

                    b.ToTable("Ventas");
                });

            modelBuilder.Entity("Tyted.API.Models.VentaDetalle", b =>
                {
                    b.Property<int>("IdDetalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDetalle"));

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<string>("CodigoProd")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("IdProductoUnidad")
                        .HasColumnType("int");

                    b.Property<decimal>("IvaLineaMonedaExt")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<string>("NombreUnidad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PrecioUnitarioMonedaBase")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("PrecioUnitarioMonedaExt")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("SubtotalLineaMonedaBase")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("SubtotalLineaMonedaExt")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("TasaIVA")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("TotalLineaMonedaBase")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("TotalLineaMonedaExt")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<int>("VentaId")
                        .HasColumnType("int");

                    b.HasKey("IdDetalle");

                    b.HasIndex("CodigoProd");

                    b.HasIndex("IdProductoUnidad");

                    b.HasIndex("VentaId");

                    b.ToTable("VentasDetalle");
                });

            modelBuilder.Entity("Tyted.API.Models.VentaPago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MetodoPago")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("MontoMonedaBase")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("MontoMonedaExt")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("TasaDeCambio")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<int>("VentaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VentaId");

                    b.ToTable("VentasPagos");
                });

            modelBuilder.Entity("Tyted.API.Models.AsientoContable", b =>
                {
                    b.HasOne("Tyted.API.Models.PeriodoContable", "PeriodoContable")
                        .WithMany("Asientos")
                        .HasForeignKey("PeriodoContableId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PeriodoContable");
                });

            modelBuilder.Entity("Tyted.API.Models.AsientoDetalle", b =>
                {
                    b.HasOne("Tyted.API.Models.AsientoContable", "AsientoContable")
                        .WithMany("Detalles")
                        .HasForeignKey("AsientoContableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tyted.API.Models.CuentaContable", "CuentaContable")
                        .WithMany()
                        .HasForeignKey("CuentaContableId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AsientoContable");

                    b.Navigation("CuentaContable");
                });

            modelBuilder.Entity("Tyted.API.Models.AuditoriaContable", b =>
                {
                    b.HasOne("Tyted.API.Models.AsientoContable", "AsientoContable")
                        .WithMany()
                        .HasForeignKey("AsientoContableId");

                    b.Navigation("AsientoContable");
                });

            modelBuilder.Entity("Tyted.API.Models.Compra", b =>
                {
                    b.HasOne("Tyted.API.Models.Proveedor", "Proveedor")
                        .WithMany("Compras")
                        .HasForeignKey("CodigoProv")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("Tyted.API.Models.CompraDetalle", b =>
                {
                    b.HasOne("Tyted.API.Models.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("CodigoProd")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tyted.API.Models.Compra", "Compra")
                        .WithMany("Detalles")
                        .HasForeignKey("CompraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Compra");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("Tyted.API.Models.CuentaContable", b =>
                {
                    b.HasOne("Tyted.API.Models.CuentaContable", "Padre")
                        .WithMany("Hijos")
                        .HasForeignKey("PadreCuentaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Padre");
                });

            modelBuilder.Entity("Tyted.API.Models.CuentaPorCobrar", b =>
                {
                    b.HasOne("Tyted.API.Models.Venta", "Venta")
                        .WithMany()
                        .HasForeignKey("VentaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("Tyted.API.Models.CuentaPorPagar", b =>
                {
                    b.HasOne("Tyted.API.Models.Compra", "Compra")
                        .WithMany()
                        .HasForeignKey("CompraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Compra");
                });

            modelBuilder.Entity("Tyted.API.Models.InventarioMovimiento", b =>
                {
                    b.HasOne("Tyted.API.Models.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("CodigoProd")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tyted.API.Models.Compra", "Compra")
                        .WithMany()
                        .HasForeignKey("CompraId");

                    b.Navigation("Compra");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("Tyted.API.Models.NotaEntregaCompraDetalle", b =>
                {
                    b.HasOne("Tyted.API.Models.NotaEntregaCompra", null)
                        .WithMany("Detalles")
                        .HasForeignKey("NotaEntregaCompraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tyted.API.Models.Pedido", b =>
                {
                    b.HasOne("Tyted.API.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Tyted.API.Models.PedidoDetalle", b =>
                {
                    b.HasOne("Tyted.API.Models.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("CodigoProd");

                    b.HasOne("Tyted.API.Models.ProductosUnidad", "ProductoUnidadNavigation")
                        .WithMany()
                        .HasForeignKey("IdProductoUnidad")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tyted.API.Models.Pedido", null)
                        .WithMany("Detalles")
                        .HasForeignKey("PedidoId");

                    b.Navigation("Producto");

                    b.Navigation("ProductoUnidadNavigation");
                });

            modelBuilder.Entity("Tyted.API.Models.Producto", b =>
                {
                    b.HasOne("Tyted.API.Models.Proveedor", "Proveedor")
                        .WithMany()
                        .HasForeignKey("CodigoProv")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tyted.API.Models.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("IdCategoria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tyted.API.Models.TasaIVA", "TasaIVA")
                        .WithMany()
                        .HasForeignKey("IdTasaIVA")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Proveedor");

                    b.Navigation("TasaIVA");
                });

            modelBuilder.Entity("Tyted.API.Models.ProductosUnidad", b =>
                {
                    b.HasOne("Tyted.API.Models.Producto", "Producto")
                        .WithMany("UnidadesDeVenta")
                        .HasForeignKey("CodigoProd")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Tyted.API.Models.UnidadMedida", "UnidadMedida")
                        .WithMany()
                        .HasForeignKey("IdUnidad")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("UnidadMedida");
                });

            modelBuilder.Entity("Tyted.API.Models.Venta", b =>
                {
                    b.HasOne("Tyted.API.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Tyted.API.Models.VentaDetalle", b =>
                {
                    b.HasOne("Tyted.API.Models.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("CodigoProd")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tyted.API.Models.ProductosUnidad", "ProductoUnidad")
                        .WithMany()
                        .HasForeignKey("IdProductoUnidad")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tyted.API.Models.Venta", "Venta")
                        .WithMany("Detalles")
                        .HasForeignKey("VentaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("ProductoUnidad");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("Tyted.API.Models.VentaPago", b =>
                {
                    b.HasOne("Tyted.API.Models.Venta", "Venta")
                        .WithMany("Pagos")
                        .HasForeignKey("VentaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("Tyted.API.Models.AsientoContable", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("Tyted.API.Models.Compra", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("Tyted.API.Models.CuentaContable", b =>
                {
                    b.Navigation("Hijos");
                });

            modelBuilder.Entity("Tyted.API.Models.NotaEntregaCompra", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("Tyted.API.Models.Pedido", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("Tyted.API.Models.PeriodoContable", b =>
                {
                    b.Navigation("Asientos");
                });

            modelBuilder.Entity("Tyted.API.Models.Producto", b =>
                {
                    b.Navigation("UnidadesDeVenta");
                });

            modelBuilder.Entity("Tyted.API.Models.Proveedor", b =>
                {
                    b.Navigation("Compras");
                });

            modelBuilder.Entity("Tyted.API.Models.Venta", b =>
                {
                    b.Navigation("Detalles");

                    b.Navigation("Pagos");
                });
#pragma warning restore 612, 618
        }
    }
}
