// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tyted.API.Data;

#nullable disable

namespace Tyted.API.Migrations
{
    [DbContext(typeof(TytedContext))]
    partial class TytedContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Compra", b =>
                {
                    b.Property<int>("IdCompra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCompra"));

                    b.Property<int>("CodigoProv")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaDocumento")
                        .HasColumnType("datetime2");

                    b.Property<string>("NumDocumento")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("ProveedorCodigoProv")
                        .HasColumnType("int");

                    b.Property<decimal>("SubTotalMonedaBase")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("TasaCambio")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<string>("TipoDoc")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("TotalCompraMonedaBase")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("TotalImpuestoMonedaBase")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("IdCompra");

                    b.HasIndex("ProveedorCodigoProv");

                    b.ToTable("Compras");
                });

            modelBuilder.Entity("CompraDetalle", b =>
                {
                    b.Property<int>("IdCompraDetalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCompraDetalle"));

                    b.Property<decimal>("CantidadComprada")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("CodigoProd")
                        .HasColumnType("int");

                    b.Property<int?>("CompraIdCompra")
                        .HasColumnType("int");

                    b.Property<decimal>("CostoUnitarioMonedaBase")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("CostoUnitarioMonedaExt")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<int>("IdCompra")
                        .HasColumnType("int");

                    b.Property<int>("IdProductoUnidad")
                        .HasColumnType("int");

                    b.Property<int?>("ProductoCodigoProd")
                        .HasColumnType("int");

                    b.Property<int?>("ProductoUnidadIdProductoUnidad")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalLineaMonedaBase")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("IdCompraDetalle");

                    b.HasIndex("CompraIdCompra");

                    b.HasIndex("ProductoCodigoProd");

                    b.HasIndex("ProductoUnidadIdProductoUnidad");

                    b.ToTable("ComprasDetalle");
                });

            modelBuilder.Entity("Tyted.API.Models.Producto", b =>
                {
                    b.Property<int>("CodigoProd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodigoProd"));

                    b.Property<string>("CodigoBarras")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CodigoProv")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("FechaAdquisicion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaVencimiento")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ProveedorCodigoProv")
                        .HasColumnType("int");

                    b.Property<decimal>("StockActual")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("TipoArt")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CodigoProd");

                    b.HasIndex("ProveedorCodigoProv");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("Tyted.API.Models.ProductosUnidad", b =>
                {
                    b.Property<int>("IdProductoUnidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProductoUnidad"));

                    b.Property<decimal>("CantidadEquivalente")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("CodigoProd")
                        .HasColumnType("int");

                    b.Property<decimal>("CostoUnitarioMonedaBase")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("CostoUnitarioMonedaExt")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<int>("IdUnidad")
                        .HasColumnType("int");

                    b.Property<string>("NombreUnidad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("PrecioMonedaBase")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("PrecioMonedaExt")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<int?>("ProductoCodigoProd")
                        .HasColumnType("int");

                    b.Property<int?>("UnidadMedidaIdUnidad")
                        .HasColumnType("int");

                    b.HasKey("IdProductoUnidad");

                    b.HasIndex("ProductoCodigoProd");

                    b.HasIndex("UnidadMedidaIdUnidad");

                    b.ToTable("ProductosUnidad");
                });

            modelBuilder.Entity("Tyted.API.Models.Proveedor", b =>
                {
                    b.Property<int>("CodigoProv")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodigoProv"));

                    b.Property<string>("Contacto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cuentaasociadaconta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonaISLR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RIF")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Razonsocial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CodigoProv");

                    b.ToTable("Proveedores");
                });

            modelBuilder.Entity("Tyted.API.Models.TasaDeCambio", b =>
                {
                    b.Property<int>("IdTasa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTasa"));

                    b.Property<DateTime>("FechaVigencia")
                        .HasColumnType("datetime2");

                    b.Property<string>("MonedaDestino")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("MonedaOrigen")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<decimal>("Tasa")
                        .HasColumnType("decimal(18, 6)");

                    b.Property<string>("UsuarioRegistro")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdTasa");

                    b.ToTable("TasasDeCambio");
                });

            modelBuilder.Entity("Tyted.API.Models.UnidadMedida", b =>
                {
                    b.Property<int>("IdUnidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUnidad"));

                    b.Property<string>("NombreUnidad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdUnidad");

                    b.ToTable("UnidadesMedida");

                    b.HasData(
                        new
                        {
                            IdUnidad = 1,
                            NombreUnidad = "Unidad"
                        },
                        new
                        {
                            IdUnidad = 2,
                            NombreUnidad = "Caja"
                        },
                        new
                        {
                            IdUnidad = 3,
                            NombreUnidad = "Paquete"
                        },
                        new
                        {
                            IdUnidad = 4,
                            NombreUnidad = "Kilogramo"
                        },
                        new
                        {
                            IdUnidad = 5,
                            NombreUnidad = "Litro"
                        });
                });

            modelBuilder.Entity("Compra", b =>
                {
                    b.HasOne("Tyted.API.Models.Proveedor", "Proveedor")
                        .WithMany()
                        .HasForeignKey("ProveedorCodigoProv");

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("CompraDetalle", b =>
                {
                    b.HasOne("Compra", "Compra")
                        .WithMany("Detalles")
                        .HasForeignKey("CompraIdCompra");

                    b.HasOne("Tyted.API.Models.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoCodigoProd");

                    b.HasOne("Tyted.API.Models.ProductosUnidad", "ProductoUnidad")
                        .WithMany()
                        .HasForeignKey("ProductoUnidadIdProductoUnidad");

                    b.Navigation("Compra");

                    b.Navigation("Producto");

                    b.Navigation("ProductoUnidad");
                });

            modelBuilder.Entity("Tyted.API.Models.Producto", b =>
                {
                    b.HasOne("Tyted.API.Models.Proveedor", "Proveedor")
                        .WithMany()
                        .HasForeignKey("ProveedorCodigoProv");

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("Tyted.API.Models.ProductosUnidad", b =>
                {
                    b.HasOne("Tyted.API.Models.Producto", "Producto")
                        .WithMany("UnidadesDeVenta")
                        .HasForeignKey("ProductoCodigoProd");

                    b.HasOne("Tyted.API.Models.UnidadMedida", "UnidadMedida")
                        .WithMany()
                        .HasForeignKey("UnidadMedidaIdUnidad");

                    b.Navigation("Producto");

                    b.Navigation("UnidadMedida");
                });

            modelBuilder.Entity("Compra", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("Tyted.API.Models.Producto", b =>
                {
                    b.Navigation("UnidadesDeVenta");
                });
#pragma warning restore 612, 618
        }
    }
}
